name: github pages

on:
  push:
    branches:
      - main

permissions:
  contents: write


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup pelican
        run: |
          pip install pelican

      - name: Build
        run: |
          pelican --delete-output-directory  content/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
